steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/proyectosm-494910/dali-repo/dali-api', '-f', 'backend/Dockerfile', '.']
images:
  - 'europe-west1-docker.pkg.dev/proyectosm-494910/dali-repo/dali-api'