steps:
  # 1. Construir la imagen Docker
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-west1-docker.pkg.dev/proyectosm-494910/dali-repo/dali-api",
        "-f",
        "backend/Dockerfile",
        ".",
      ]

  # 2. Subir la imagen a Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "europe-west1-docker.pkg.dev/proyectosm-494910/dali-repo/dali-api"]

  # 3. Desplegar en Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "dal-i-api"
      - "--image"
      - "europe-west1-docker.pkg.dev/proyectosm-494910/dali-repo/dali-api"
      - "--region"
      - "europe-west1"
      - "--allow-unauthenticated"

images:
  - "europe-west1-docker.pkg.dev/proyectosm-494910/dali-repo/dali-api"

options:
  logging: CLOUD_LOGGING_ONLY